<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "formline".
 *
 * @property int $id
 * @property int $form_id
 * @property string $type
 * @property string $annotation
 *
 * @property Formanswer[] $formanswers
 * @property Formtable $form
 */
class Formline extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'formline';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['form_id'], 'integer'],
            [['type', 'annotation'], 'string', 'max' => 255],
            [['form_id'], 'exist', 'skipOnError' => true, 'targetClass' => Formtable::className(), 'targetAttribute' => ['form_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'form_id' => 'Form ID',
            'type' => 'Type',
            'annotation' => 'Annotation',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFormanswers()
    {
        return $this->hasMany(Formanswer::className(), ['line_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getForm()
    {
        return $this->hasOne(Formtable::className(), ['id' => 'form_id']);
    }

    public function beforeDelete()
    {
        $models = Formanswer::find()->where(['line_id'=>$this->id])->all();
        foreach ($models as $model){
            $model->delete();
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
